[package]
name    = "mosek"
version = "0.1.0"
authors = [ "Ulf Wors√∏e <ulf.worsoe@mosek.com>" ]
description = "Rust API for MOSEK optimization tools"

build = "build.rs"

license = "BSD-4-Clause"

[dependencies]
libc = "0.2"
